[versions]
# libraries
junit = "4.13.2"

# plugins
changelog = "2.2.1"
ktlint = "12.1.2"
intelliJPlatform = "2.10.4"
kotlin = "1.9.25"
#intelliJPlatform = "2.7.0"
#kotlin = "2.1.21"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
